vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        articles:
            uri_prefix: /images/articles
            #%kernel.project_dir c'est le chemin complet de mon appli
            # tu lui défini le chemin
            upload_destination: '%kernel.project_dir%/public/images/articles'
            # c'est comment tu nome ton image
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # Va créer un sous dossier au nom de ton article en te le générant
            directory_namer: 
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options: { property: 'title', transiterate: true }
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #exemple de mapping
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
